<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adicional extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Adicional_model');
    } 

    /*
     * Listing of adicionais
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('adicional/index?');
        $config['total_rows'] = $this->Adicional_model->get_all_adicionais_count();
        $this->pagination->initialize($config);

        $data['adicionais'] = $this->Adicional_model->get_all_adicionais($params);
        
        $data['_view'] = 'adicional/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new adicional
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nome','Nome','required');
		$this->form_validation->set_rules('valor','Valor','decimal|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nome' => $this->input->post('nome'),
				'custo' => $this->input->post('custo'),
				'valor' => $this->input->post('valor'),
				'status' => $this->input->post('status'),
            );
            
            $adicional_id = $this->Adicional_model->add_adicional($params);
            redirect('adicional/index');
        }
        else
        {            
            $data['_view'] = 'adicional/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a adicional
     */
    function edit($idadicionais)
    {   
        // check if the adicional exists before trying to edit it
        $data['adicional'] = $this->Adicional_model->get_adicional($idadicionais);
        
        if(isset($data['adicional']['idadicionais']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nome','Nome','required');
			$this->form_validation->set_rules('valor','Valor','decimal|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nome' => $this->input->post('nome'),
					'custo' => $this->input->post('custo'),
					'valor' => $this->input->post('valor'),
					'status' => $this->input->post('status'),
                );

                $this->Adicional_model->update_adicional($idadicionais,$params);            
                redirect('adicional/index');
            }
            else
            {
                $data['_view'] = 'adicional/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The adicional you are trying to edit does not exist.');
    } 

    /*
     * Deleting adicional
     */
    function remove($idadicionais)
    {
        $adicional = $this->Adicional_model->get_adicional($idadicionais);

        // check if the adicional exists before trying to delete it
        if(isset($adicional['idadicionais']))
        {
            $this->Adicional_model->delete_adicional($idadicionais);
            redirect('adicional/index');
        }
        else
            show_error('The adicional you are trying to delete does not exist.');
    }
    
}
