<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Caixa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Caixa_model');
    } 

    /*
     * Listing of caixa
     */
    function index()
    {
        $data['caixa'] = $this->Caixa_model->get_all_caixa();
        
        $data['_view'] = 'caixa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new caixa
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'data' => $this->input->post('data'),
				'valor' => $this->input->post('valor'),
				'descricao' => $this->input->post('descricao'),
				'idformaspagamento' => $this->input->post('idformaspagamento'),
				'tipomovimentacao' => $this->input->post('tipomovimentacao'),
				'usuario_id' => $this->input->post('usuario_id'),
            );
            
            $caixa_id = $this->Caixa_model->add_caixa($params);
            redirect('caixa/index');
        }
        else
        {            
            $data['_view'] = 'caixa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a caixa
     */
    function edit($idcaixa)
    {   
        // check if the caixa exists before trying to edit it
        $data['caixa'] = $this->Caixa_model->get_caixa($idcaixa);
        
        if(isset($data['caixa']['idcaixa']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'data' => $this->input->post('data'),
					'valor' => $this->input->post('valor'),
					'descricao' => $this->input->post('descricao'),
					'idformaspagamento' => $this->input->post('idformaspagamento'),
					'tipomovimentacao' => $this->input->post('tipomovimentacao'),
					'usuario_id' => $this->input->post('usuario_id'),
                );

                $this->Caixa_model->update_caixa($idcaixa,$params);            
                redirect('caixa/index');
            }
            else
            {
                $data['_view'] = 'caixa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The caixa you are trying to edit does not exist.');
    } 

    /*
     * Deleting caixa
     */
    function remove($idcaixa)
    {
        $caixa = $this->Caixa_model->get_caixa($idcaixa);

        // check if the caixa exists before trying to delete it
        if(isset($caixa['idcaixa']))
        {
            $this->Caixa_model->delete_caixa($idcaixa);
            redirect('caixa/index');
        }
        else
            show_error('The caixa you are trying to delete does not exist.');
    }
    
}
