<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cliente extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cliente_model');
    } 

    /*
     * Listing of clientes
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('cliente/index?');
        $config['total_rows'] = $this->Cliente_model->get_all_clientes_count();
        $this->pagination->initialize($config);

        $data['clientes'] = $this->Cliente_model->get_all_clientes($params);
        
        $data['_view'] = 'cliente/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cliente
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nome','Nome','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'ativo' => $this->input->post('ativo'),
				'nome' => $this->input->post('nome'),
				'rg' => $this->input->post('rg'),
				'datanasc' => $this->input->post('datanasc'),
				'telfixo' => $this->input->post('telfixo'),
				'celular' => $this->input->post('celular'),
				'cpf' => $this->input->post('cpf'),
				'rua' => $this->input->post('rua'),
				'numero' => $this->input->post('numero'),
				'bairro' => $this->input->post('bairro'),
				'cidade' => $this->input->post('cidade'),
				'saldodevedor' => $this->input->post('saldodevedor'),
				'observacao' => $this->input->post('observacao'),
				'datacadastro' => $this->input->post('datacadastro'),
            );
            
            $cliente_id = $this->Cliente_model->add_cliente($params);
            redirect('cliente/index');
        }
        else
        {            
            $data['_view'] = 'cliente/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cliente
     */
    function edit($idclientes)
    {   
        // check if the cliente exists before trying to edit it
        $data['cliente'] = $this->Cliente_model->get_cliente($idclientes);
        
        if(isset($data['cliente']['idclientes']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nome','Nome','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'ativo' => $this->input->post('ativo'),
					'nome' => $this->input->post('nome'),
					'rg' => $this->input->post('rg'),
					'datanasc' => $this->input->post('datanasc'),
					'telfixo' => $this->input->post('telfixo'),
					'celular' => $this->input->post('celular'),
					'cpf' => $this->input->post('cpf'),
					'rua' => $this->input->post('rua'),
					'numero' => $this->input->post('numero'),
					'bairro' => $this->input->post('bairro'),
					'cidade' => $this->input->post('cidade'),
					'saldodevedor' => $this->input->post('saldodevedor'),
					'observacao' => $this->input->post('observacao'),
					'datacadastro' => $this->input->post('datacadastro'),
                );

                $this->Cliente_model->update_cliente($idclientes,$params);            
                redirect('cliente/index');
            }
            else
            {
                $data['_view'] = 'cliente/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cliente you are trying to edit does not exist.');
    } 

    /*
     * Deleting cliente
     */
    function remove($idclientes)
    {
        $cliente = $this->Cliente_model->get_cliente($idclientes);

        // check if the cliente exists before trying to delete it
        if(isset($cliente['idclientes']))
        {
            $this->Cliente_model->delete_cliente($idclientes);
            redirect('cliente/index');
        }
        else
            show_error('The cliente you are trying to delete does not exist.');
    }
    
}
