<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Configuracoes extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Empresa_model');
    }


public function index(){
      $data['empresa'] = $this->Empresa_model->get_all_empresa();

          $data['_view'] = 'configuracoes/configuracoes';
          $this->load->view('layouts/main',$data);
}
  }
