<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Controlesistema extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->database('sistema',TRUE);
            $this->load->model('Controlesistema_model');

    }

    public function index(){

      $data['sistema']= $this->Controlesistema_model->getsistema();

      return $data;
    }
}
