<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Contasapagar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Contasapagar_model');
    }

    /*
     * Listing of contasapagar
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('contaapagar/index?');
        $config['total_rows'] = $this->Contasapagar_model->get_all_contasapagar_count();
        $this->pagination->initialize($config);

        $data['contasapagar'] = $this->Contasapagar_model->get_all_contasapagar($params);

        $data['_view'] = 'contasapagar/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new contaapagar
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('datavencimento','Datavencimento','required');
		$this->form_validation->set_rules('valorconta','Valorconta','required');

		if($this->form_validation->run())
        {
            $params = array(
				'datavencimento' => $this->input->post('datavencimento'),
				'datapagamento' => $this->input->post('datapagamento'),
				'valorconta' => $this->input->post('valorconta'),
				'desconto' => $this->input->post('desconto'),
				'valorpago' => $this->input->post('valorpago'),

				'status' => $this->input->post('status'),
				'datalanc' => $this->input->post('datalanc'),
				'descricao' => $this->input->post('descricao'),
				'numerodoc' => $this->input->post('numerodoc'),
				'tipomovimentacao' => $this->input->post('tipomovimentacao'),
            );

            $contaapagar_id = $this->Contasapagar_model->add_contaapagar($params);
            redirect('contasapagar/index');
        }
        else
        {
            $data['_view'] = 'contasapagar/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a contaapagar
     */

     function recebeconta($id){

 date_default_timezone_set('America/Sao_Paulo');
       $params = array(
         'formarecebimento'=>$this->input->post('formarecebimento'),
          'datapagamento' =>  date('d/m/Y'),
        	'valorpago' => $this->input->post('valorpago')

       );

       $null = $this->Contasapagar_model->update_contaapagar($id,$params);


       $tipomov='2';
       $descricao = "PAGAMENTO REF ". $this->input->post('descricaoconta');
         $fluxo = array(
             'formapagto'=> $this->input->post('formarecebimento'),
             'data'=>  date('d/m/Y'),
             'valor'=>$this->input->post('valorpago'),
             'descricao'=>$descricao,
             'tipomovimentacao'=>$tipomov
         );

       $this->load->model('Caixa_model');
         $this->Caixa_model->add_caixa($fluxo);

       redirect('contasapagar/index');

     }


    function edit($idcontasapagar)
    {
        // check if the contaapagar exists before trying to edit it
        $data['contaapagar'] = $this->Contasapagar_model->get_contaapagar($idcontasapagar);

        if(isset($data['contaapagar']['idcontasapagar']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('datavencimento','Datavencimento','required');
			$this->form_validation->set_rules('valorconta','Valorconta','required');

			if($this->form_validation->run())
            {
                $params = array(
					'datavencimento' => $this->input->post('datavencimento'),
					'datapagamento' => $this->input->post('datapagamento'),
					'valorconta' => $this->input->post('valorconta'),
					'desconto' => $this->input->post('desconto'),
					'valorpago' => $this->input->post('valorpago'),

					'status' => $this->input->post('status'),
					'datalanc' => $this->input->post('datalanc'),
					'descricao' => $this->input->post('descricao'),
					'numerodoc' => $this->input->post('numerodoc'),
					'tipomovimentacao' => $this->input->post('tipomovimentacao'),
                );

                $this->Contasapagar_model->update_contaapagar($idcontasapagar,$params);
                redirect('contasapagar/index');
            }
            else
            {
                $data['_view'] = 'contasapagar/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The contaapagar you are trying to edit does not exist.');
    }

    /*
     * Deleting contaapagar
     */
    function remove($idcontasapagar)
    {
        $contaapagar = $this->Contasapagar_model->get_contaapagar($idcontasapagar);

        // check if the contaapagar exists before trying to delete it
        if(isset($contaapagar['idcontasapagar']))
        {
            $this->Contasapagar_model->delete_contaapagar($idcontasapagar);
            redirect('contasapagar/index');
        }
        else
            show_error('The contaapagar you are trying to delete does not exist.');
    }

}
