<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Entregador extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Entregador_model');
    } 

    /*
     * Listing of entregadores
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('entregador/index?');
        $config['total_rows'] = $this->Entregador_model->get_all_entregadores_count();
        $this->pagination->initialize($config);

        $data['entregadores'] = $this->Entregador_model->get_all_entregadores($params);
        
        $data['_view'] = 'entregador/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new entregador
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nome','Nome','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nome' => $this->input->post('nome'),
				'telefone' => $this->input->post('telefone'),
				'celular' => $this->input->post('celular'),
				'observacao' => $this->input->post('observacao'),
				'status' => $this->input->post('status'),
            );
            
            $entregador_id = $this->Entregador_model->add_entregador($params);
            redirect('entregador/index');
        }
        else
        {            
            $data['_view'] = 'entregador/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a entregador
     */
    function edit($identregador)
    {   
        // check if the entregador exists before trying to edit it
        $data['entregador'] = $this->Entregador_model->get_entregador($identregador);
        
        if(isset($data['entregador']['identregador']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nome','Nome','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nome' => $this->input->post('nome'),
					'telefone' => $this->input->post('telefone'),
					'celular' => $this->input->post('celular'),
					'observacao' => $this->input->post('observacao'),
					'status' => $this->input->post('status'),
                );

                $this->Entregador_model->update_entregador($identregador,$params);            
                redirect('entregador/index');
            }
            else
            {
                $data['_view'] = 'entregador/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The entregador you are trying to edit does not exist.');
    } 

    /*
     * Deleting entregador
     */
    function remove($identregador)
    {
        $entregador = $this->Entregador_model->get_entregador($identregador);

        // check if the entregador exists before trying to delete it
        if(isset($entregador['identregador']))
        {
            $this->Entregador_model->delete_entregador($identregador);
            redirect('entregador/index');
        }
        else
            show_error('The entregador you are trying to delete does not exist.');
    }
    
}
