<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Formaspagamento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Formaspagamento_model');
    } 

    /*
     * Listing of formaspagamento
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('formapagamento/index?');
        $config['total_rows'] = $this->Formaspagamento_model->get_all_formaspagamento_count();
        $this->pagination->initialize($config);

        $data['formaspagamento'] = $this->Formaspagamento_model->get_all_formaspagamento($params);
        
        $data['_view'] = 'formaspagamento/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new formapagamento
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nome' => $this->input->post('nome'),
				'tipopagamento' => $this->input->post('tipopagamento'),
				'numeroparcelas' => $this->input->post('numeroparcelas'),
				'prazoentreparcelas' => $this->input->post('prazoentreparcelas'),
            );
            
            $formapagamento_id = $this->Formaspagamento_model->add_formapagamento($params);
            redirect('formaspagamento/index');
        }
        else
        {            
            $data['_view'] = 'formaspagamento/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a formapagamento
     */
    function edit($idformaspagamento)
    {   
        // check if the formapagamento exists before trying to edit it
        $data['formapagamento'] = $this->Formaspagamento_model->get_formapagamento($idformaspagamento);
        
        if(isset($data['formapagamento']['idformaspagamento']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nome' => $this->input->post('nome'),
					'tipopagamento' => $this->input->post('tipopagamento'),
					'numeroparcelas' => $this->input->post('numeroparcelas'),
					'prazoentreparcelas' => $this->input->post('prazoentreparcelas'),
                );

                $this->Formaspagamento_model->update_formapagamento($idformaspagamento,$params);            
                redirect('formaspagamento/index');
            }
            else
            {
                $data['_view'] = 'formaspagamento/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The formapagamento you are trying to edit does not exist.');
    } 

    /*
     * Deleting formapagamento
     */
    function remove($idformaspagamento)
    {
        $formapagamento = $this->Formaspagamento_model->get_formapagamento($idformaspagamento);

        // check if the formapagamento exists before trying to delete it
        if(isset($formapagamento['idformaspagamento']))
        {
            $this->Formaspagamento_model->delete_formapagamento($idformaspagamento);
            redirect('formaspagamento/index');
        }
        else
            show_error('The formapagamento you are trying to delete does not exist.');
    }
    
}
