<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Impressoras extends CI_Controller{
    function __construct()
    {

    }

    function impressaoteste(){

        require __DIR__ .'/../third_party/Mike42/escpos-php/autoload.php';
        use Mike42\Escpos\Printer;
        use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

        
       try {
           // Enter the share name for your USB printer here
           $connector = null;
           //$connector = new WindowsPrintConnector("Receipt Printer");

           /* Print a "Hello world" receipt" */
           $printer = new Printer($connector);
           $printer -> text("Hello World!\n");
           $printer -> cut();

           /* Close printer */
           $printer -> close();
       } catch (Exception $e) {
           echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
       }
    }
  }
