<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

 use Mike42\Escpos\Printer;
 use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

 //use Mike42\Escpos\Printer;
 //use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
class Impressoras extends CI_Controller{

  public function __construct() {
   parent::__construct();
  // $this->load->library('escpos');


}

    function impressaoteste(){


      try {
      		// Enter the device file for your USB printer here
      	  $connector = new Escpos\PrintConnectors\WindowsPrintConnector("itautec");

      		/* Print a "Hello world" receipt" */
      		$printer = new Escpos\Printer($connector);
      		$printer -> text("Hello World!\n");
      		$printer -> cut();

      		/* Close printer */
      		$printer -> close();
      } catch (Exception $e) {
      	echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
      }





    }
  }
