<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itensinventario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Itensinventario_model');
    } 

    /*
     * Listing of itensinventario
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('iteminventario/index?');
        $config['total_rows'] = $this->Itensinventario_model->get_all_itensinventario_count();
        $this->pagination->initialize($config);

        $data['itensinventario'] = $this->Itensinventario_model->get_all_itensinventario($params);
        
        $data['_view'] = 'itensinventario/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new iteminventario
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idinventario' => $this->input->post('idinventario'),
				'produto_id' => $this->input->post('produto_id'),
				'nomeproduto' => $this->input->post('nomeproduto'),
				'codbarra' => $this->input->post('codbarra'),
				'quantidade' => $this->input->post('quantidade'),
				'time' => $this->input->post('time'),
            );
            
            $iteminventario_id = $this->Itensinventario_model->add_iteminventario($params);
            redirect('itensinventario/index');
        }
        else
        {            
            $data['_view'] = 'itensinventario/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a iteminventario
     */
    function edit($iditensinventario)
    {   
        // check if the iteminventario exists before trying to edit it
        $data['iteminventario'] = $this->Itensinventario_model->get_iteminventario($iditensinventario);
        
        if(isset($data['iteminventario']['iditensinventario']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idinventario' => $this->input->post('idinventario'),
					'produto_id' => $this->input->post('produto_id'),
					'nomeproduto' => $this->input->post('nomeproduto'),
					'codbarra' => $this->input->post('codbarra'),
					'quantidade' => $this->input->post('quantidade'),
					'time' => $this->input->post('time'),
                );

                $this->Itensinventario_model->update_iteminventario($iditensinventario,$params);            
                redirect('itensinventario/index');
            }
            else
            {
                $data['_view'] = 'itensinventario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The iteminventario you are trying to edit does not exist.');
    } 

    /*
     * Deleting iteminventario
     */
    function remove($iditensinventario)
    {
        $iteminventario = $this->Itensinventario_model->get_iteminventario($iditensinventario);

        // check if the iteminventario exists before trying to delete it
        if(isset($iteminventario['iditensinventario']))
        {
            $this->Itensinventario_model->delete_iteminventario($iditensinventario);
            redirect('itensinventario/index');
        }
        else
            show_error('The iteminventario you are trying to delete does not exist.');
    }
    
}
