<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Itenspedidopdv extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Itenspedidopdv_model');
        $this->load->model('Saidaproduto_model');
    }

    /*
     * Listing of itenspedidopdv
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('itempedidopdv/index?');
        $config['total_rows'] = $this->Itenspedidopdv_model->get_all_itenspedidopdv_count();
        $this->pagination->initialize($config);

        $data['itenspedidopdv'] = $this->Itenspedidopdv_model->get_all_itenspedidopdv($params);

        $data['_view'] = 'itenspedidopdv/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new itempedidopdv
     */
    function add()
    {


      date_default_timezone_set('America/Sao_Paulo');
      $data = date('d/m/Y');
      $hora = date('H:i');
            $params = array(
	'idpedidopdv' => $this->input->post('idpedidopdv'),
				'produto_id' => $this->input->post('produto_id'),
				'nomeproduto' => $this->input->post('nomeproduto'),
				'quantidade' => $this->input->post('quantidade'),
        'codbarra' => $this->input->post('codbarra'),
				'valor' => $this->input->post('valor'),
				'hora' => $hora,
				'data' => $data,
				'usuario_id' => $this->input->post('usuario_id')
            );

            $itempedidopdv_id = $this->Itenspedidopdv_model->add_itempedidopdv($params);

            $saida = array(
              'id_produto'=>$this->input->post('produto_id'),
              'qtde'=>$this->input->post('quantidade'),
              'valor_unitario'=>$this->input->post('valor')
            );

            $itempedidopdv_id = $this->Saidaproduto_model->saida($saida);
            echo json_encode(array('result'=> true));

    }

    /*
     * Editing a itempedidopdv
     */
    function edit($iditenspedidodelivery)
    {
        // check if the itempedidopdv exists before trying to edit it
        $data['itempedidopdv'] = $this->Itenspedidopdv_model->get_itempedidopdv($iditenspedidodelivery);

        if(isset($data['itempedidopdv']['iditenspedidodelivery']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'idpedidopdv' => $this->input->post('idpedidopdv'),
					'produto_id' => $this->input->post('produto_id'),
					'nomeproduto' => $this->input->post('nomeproduto'),
					'quantidade' => $this->input->post('quantidade'),
					'valor' => $this->input->post('valor'),
					'hora' => $this->input->post('hora'),
					'data' => $this->input->post('data'),
					'usuario_id' => $this->input->post('usuario_id'),
                );

                $this->Itenspedidopdv_model->update_itempedidopdv($iditenspedidodelivery,$params);
                redirect('itenspedidopdv/index');
            }
            else
            {
                $data['_view'] = 'itenspedidopdv/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The itempedidopdv you are trying to edit does not exist.');
    }

    /*
     * Deleting itempedidopdv
     */
    function remove()
    {
$iditenspedidodelivery = $this->input->post('iditenspedidodelivery');
            $this->Itenspedidopdv_model->delete_itempedidopdv($iditenspedidodelivery);
            echo json_encode(array('result'=> true));
        }


}
