<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Menu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Menu_model');
    } 

    /*
     * Listing of menu
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('menu/index?');
        $config['total_rows'] = $this->Menu_model->get_all_menu_count();
        $this->pagination->initialize($config);

        $data['menu'] = $this->Menu_model->get_all_menu($params);
        
        $data['_view'] = 'menu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new menu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'pedidobalcao' => $this->input->post('pedidobalcao'),
				'pedidomesa' => $this->input->post('pedidomesa'),
				'pedidopdvtouch' => $this->input->post('pedidopdvtouch'),
				'pedidopdvean' => $this->input->post('pedidopdvean'),
				'pedidodelivery' => $this->input->post('pedidodelivery'),
				'pedidomobile' => $this->input->post('pedidomobile'),
				'clientes' => $this->input->post('clientes'),
				'produtos' => $this->input->post('produtos'),
				'produtovariaveis' => $this->input->post('produtovariaveis'),
				'categorias' => $this->input->post('categorias'),
				'adicionais' => $this->input->post('adicionais'),
				'observacoes' => $this->input->post('observacoes'),
				'contaspagar' => $this->input->post('contaspagar'),
				'contasreceber' => $this->input->post('contasreceber'),
				'caixa' => $this->input->post('caixa'),
				'fornecedores' => $this->input->post('fornecedores'),
				'entradanota' => $this->input->post('entradanota'),
				'inventario' => $this->input->post('inventario'),
            );
            
            $menu_id = $this->Menu_model->add_menu($params);
            redirect('menu/index');
        }
        else
        {            
            $data['_view'] = 'menu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a menu
     */
    function edit($idtipodevendas)
    {   
        // check if the menu exists before trying to edit it
        $data['menu'] = $this->Menu_model->get_menu($idtipodevendas);
        
        if(isset($data['menu']['idtipodevendas']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'pedidobalcao' => $this->input->post('pedidobalcao'),
					'pedidomesa' => $this->input->post('pedidomesa'),
					'pedidopdvtouch' => $this->input->post('pedidopdvtouch'),
					'pedidopdvean' => $this->input->post('pedidopdvean'),
					'pedidodelivery' => $this->input->post('pedidodelivery'),
					'pedidomobile' => $this->input->post('pedidomobile'),
					'clientes' => $this->input->post('clientes'),
					'produtos' => $this->input->post('produtos'),
					'produtovariaveis' => $this->input->post('produtovariaveis'),
					'categorias' => $this->input->post('categorias'),
					'adicionais' => $this->input->post('adicionais'),
					'observacoes' => $this->input->post('observacoes'),
					'contaspagar' => $this->input->post('contaspagar'),
					'contasreceber' => $this->input->post('contasreceber'),
					'caixa' => $this->input->post('caixa'),
					'fornecedores' => $this->input->post('fornecedores'),
					'entradanota' => $this->input->post('entradanota'),
					'inventario' => $this->input->post('inventario'),
                );

                $this->Menu_model->update_menu($idtipodevendas,$params);            
                redirect('menu/index');
            }
            else
            {
                $data['_view'] = 'menu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The menu you are trying to edit does not exist.');
    } 

    /*
     * Deleting menu
     */
    function remove($idtipodevendas)
    {
        $menu = $this->Menu_model->get_menu($idtipodevendas);

        // check if the menu exists before trying to delete it
        if(isset($menu['idtipodevendas']))
        {
            $this->Menu_model->delete_menu($idtipodevendas);
            redirect('menu/index');
        }
        else
            show_error('The menu you are trying to delete does not exist.');
    }
    
}
