<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Observaco extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Observaco_model');
    } 

    /*
     * Listing of observacoes
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('observacao/index?');
        $config['total_rows'] = $this->Observaco_model->get_all_observacoes_count();
        $this->pagination->initialize($config);

        $data['observacoes'] = $this->Observaco_model->get_all_observacoes($params);
        
        $data['_view'] = 'observaco/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new observacao
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nome','Nome','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nome' => $this->input->post('nome'),
            );
            
            $observacao_id = $this->Observaco_model->add_observacao($params);
            redirect('observaco/index');
        }
        else
        {            
            $data['_view'] = 'observaco/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a observacao
     */
    function edit($idobservacoes)
    {   
        // check if the observacao exists before trying to edit it
        $data['observacao'] = $this->Observaco_model->get_observacao($idobservacoes);
        
        if(isset($data['observacao']['idobservacoes']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nome','Nome','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nome' => $this->input->post('nome'),
                );

                $this->Observaco_model->update_observacao($idobservacoes,$params);            
                redirect('observaco/index');
            }
            else
            {
                $data['_view'] = 'observaco/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The observacao you are trying to edit does not exist.');
    } 

    /*
     * Deleting observacao
     */
    function remove($idobservacoes)
    {
        $observacao = $this->Observaco_model->get_observacao($idobservacoes);

        // check if the observacao exists before trying to delete it
        if(isset($observacao['idobservacoes']))
        {
            $this->Observaco_model->delete_observacao($idobservacoes);
            redirect('observaco/index');
        }
        else
            show_error('The observacao you are trying to delete does not exist.');
    }
    
}
