<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Opcoesitempedidodelivery extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Opcoesitempedidodelivery_model');
    } 

    /*
     * Listing of opcoesitempedidodelivery
     */
    function index()
    {
        $data['opcoesitempedidodelivery'] = $this->Opcoesitempedidodelivery_model->get_all_opcoesitempedidodelivery();
        
        $data['_view'] = 'opcoesitempedidodelivery/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new opcoesitempedidodelivery
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'iditenspedidodelivery' => $this->input->post('iditenspedidodelivery'),
				'idadicionais' => $this->input->post('idadicionais'),
				'valor_adicional' => $this->input->post('valor_adicional'),
				'observacao' => $this->input->post('observacao'),
				'idpedidodelivery' => $this->input->post('idpedidodelivery'),
				'nome' => $this->input->post('nome'),
				'tipoopcao' => $this->input->post('tipoopcao'),
				'idobservacao' => $this->input->post('idobservacao'),
            );
            
            $opcoesitempedidodelivery_id = $this->Opcoesitempedidodelivery_model->add_opcoesitempedidodelivery($params);
            redirect('opcoesitempedidodelivery/index');
        }
        else
        {            
            $data['_view'] = 'opcoesitempedidodelivery/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a opcoesitempedidodelivery
     */
    function edit($idopcoesitempedidomesa)
    {   
        // check if the opcoesitempedidodelivery exists before trying to edit it
        $data['opcoesitempedidodelivery'] = $this->Opcoesitempedidodelivery_model->get_opcoesitempedidodelivery($idopcoesitempedidomesa);
        
        if(isset($data['opcoesitempedidodelivery']['idopcoesitempedidomesa']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'iditenspedidodelivery' => $this->input->post('iditenspedidodelivery'),
					'idadicionais' => $this->input->post('idadicionais'),
					'valor_adicional' => $this->input->post('valor_adicional'),
					'observacao' => $this->input->post('observacao'),
					'idpedidodelivery' => $this->input->post('idpedidodelivery'),
					'nome' => $this->input->post('nome'),
					'tipoopcao' => $this->input->post('tipoopcao'),
					'idobservacao' => $this->input->post('idobservacao'),
                );

                $this->Opcoesitempedidodelivery_model->update_opcoesitempedidodelivery($idopcoesitempedidomesa,$params);            
                redirect('opcoesitempedidodelivery/index');
            }
            else
            {
                $data['_view'] = 'opcoesitempedidodelivery/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The opcoesitempedidodelivery you are trying to edit does not exist.');
    } 

    /*
     * Deleting opcoesitempedidodelivery
     */
    function remove($idopcoesitempedidomesa)
    {
        $opcoesitempedidodelivery = $this->Opcoesitempedidodelivery_model->get_opcoesitempedidodelivery($idopcoesitempedidomesa);

        // check if the opcoesitempedidodelivery exists before trying to delete it
        if(isset($opcoesitempedidodelivery['idopcoesitempedidomesa']))
        {
            $this->Opcoesitempedidodelivery_model->delete_opcoesitempedidodelivery($idopcoesitempedidomesa);
            redirect('opcoesitempedidodelivery/index');
        }
        else
            show_error('The opcoesitempedidodelivery you are trying to delete does not exist.');
    }
    
}
