<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pagamentopedidomesa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pagamentopedidomesa_model');
        $this->load->model('Pedidomesa_model');
        $this->load->model('Mesasaberta_model');
            $this->load->model('Caixa_model');
    }

    /*
     * Listing of pagamentopedidomesa
     */
    function index()
    {
        $data['pagamentopedidomesa'] = $this->Pagamentopedidomesa_model->get_all_pagamentopedidomesa();

        $data['_view'] = 'pagamentopedidomesa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pagamentopedidomesa
     */
    function add()
    {

      $idpedidomesa = $this->input->post('idpedidopagamento');
      $totalpago = $this->input->post('valorpago');
      $vlrpgto = $this->input->post('vlrpgto');
      $totalpedido = $this->input->post('subtotalpagamento');

      if($vlrpgto>=($totalpedido-$totalpago)){

        $vlr = ($totalpedido-$totalpago);
        $params = array(
    'idpedidomesa' => $idpedidomesa,
    'data'=>$this->input->post('data'),
    'valor' => number_format((float)$vlr,2,'.',''),
    'descricao' => $this->input->post('descricao'),
  //	'idformapagamento' => $this->input->post('idformapagamento'),
  //	'data' => $this->input->post('data'),
    'tipomovimentacao' => $this->input->post('tipomovimentacao'),
  //	'usuario_id' => $this->input->post('usuario_id'),
    'formapagto' => $this->input->post('formapgtoselecionada')
  );

  $pagamentopedidomesa_id = $this->Pagamentopedidomesa_model->add_pagamentopedidomesa($params);
$this->Mesasaberta_model->delete_mesasaberta($idpedidomesa);

$caixa = array(
      'data'=>$this->input->post('data'),
      'valor'=> number_format((float)$vlr,2,'.',''),
      'descricao'=>$this->input->post('descricao'),
        'tipomovimentacao' => $this->input->post('tipomovimentacao'),
          'formapagto' => $this->input->post('formapgtoselecionada')

);

  $this->Caixa_model->add_caixa($caixa);
  echo json_encode(array('result'=> false));
}

else{


            $params = array(
				'idpedidomesa' => $idpedidomesa,
				'valor' =>$this->input->post('vlrpgto'),
				'descricao' => $this->input->post('descricao'),
			//	'idformapagamento' => $this->input->post('idformapagamento'),
			//	'data' => $this->input->post('data'),
				'tipomovimentacao' => $this->input->post('tipomovimentacao'),
			//	'usuario_id' => $this->input->post('usuario_id'),
				'formapagto' => $this->input->post('formapgtoselecionada')
      );
          $pagamentopedidomesa_id = $this->Pagamentopedidomesa_model->add_pagamentopedidomesa($params);
          echo json_encode(array('result'=> true));

          $caixa = array(
                'data'=>$this->input->post('data'),
                'valor'=> $this->input->post('vlrpgto'),
                'descricao'=>$this->input->post('descricao'),
                  'tipomovimentacao' => $this->input->post('tipomovimentacao'),
                    'formapagto' => $this->input->post('formapgtoselecionada')

          );

            $this->Caixa_model->add_caixa($caixa);
}







          //  $data['_view'] = 'pagamentopedidomesa/add';
        //    $this->load->view('layouts/main',$data);

    }

    /*
     * Editing a pagamentopedidomesa
     */
    function edit($idpagamentopedidomesa)
    {
        // check if the pagamentopedidomesa exists before trying to edit it
        $data['pagamentopedidomesa'] = $this->Pagamentopedidomesa_model->get_pagamentopedidomesa($idpagamentopedidomesa);

        if(isset($data['pagamentopedidomesa']['idpagamentopedidomesa']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'idpedidomesa' => $this->input->post('idpedidomesa'),
					'valor' => $this->input->post('valor'),
					'descricao' => $this->input->post('descricao'),
					'idformapagamento' => $this->input->post('idformapagamento'),
					'data' => $this->input->post('data'),
					'tipomovimentacao' => $this->input->post('tipomovimentacao'),
					'usuario_id' => $this->input->post('usuario_id'),
					'formapagto' => $this->input->post('formapagto'),
                );

                $this->Pagamentopedidomesa_model->update_pagamentopedidomesa($idpagamentopedidomesa,$params);
                redirect('pagamentopedidomesa/index');
            }
            else
            {
                $data['_view'] = 'pagamentopedidomesa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pagamentopedidomesa you are trying to edit does not exist.');
    }

    /*
     * Deleting pagamentopedidomesa
     */
    function remove($idpagamentopedidomesa)
    {
        $pagamentopedidomesa = $this->Pagamentopedidomesa_model->get_pagamentopedidomesa($idpagamentopedidomesa);

        // check if the pagamentopedidomesa exists before trying to delete it
        if(isset($pagamentopedidomesa['idpagamentopedidomesa']))
        {
            $this->Pagamentopedidomesa_model->delete_pagamentopedidomesa($idpagamentopedidomesa);
            redirect('pagamentopedidomesa/index');
        }
        else
            show_error('The pagamentopedidomesa you are trying to delete does not exist.');
    }

}
