<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pagamentopedidodelivery extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pagamentopedidodelivery_model');
    } 

    /*
     * Listing of pagamentopedidodelivery
     */
    function index()
    {
        $data['pagamentopedidodelivery'] = $this->Pagamentopedidodelivery_model->get_all_pagamentopedidodelivery();
        
        $data['_view'] = 'pagamentopedidodelivery/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pagamentopedidodelivery
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idpedidodelivery' => $this->input->post('idpedidodelivery'),
				'valor' => $this->input->post('valor'),
				'descricao' => $this->input->post('descricao'),
				'idformapagamento' => $this->input->post('idformapagamento'),
				'data' => $this->input->post('data'),
				'tipomovimentacao' => $this->input->post('tipomovimentacao'),
				'usuario_id' => $this->input->post('usuario_id'),
				'formapgto' => $this->input->post('formapgto'),
            );
            
            $pagamentopedidodelivery_id = $this->Pagamentopedidodelivery_model->add_pagamentopedidodelivery($params);
            redirect('pagamentopedidodelivery/index');
        }
        else
        {            
            $data['_view'] = 'pagamentopedidodelivery/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pagamentopedidodelivery
     */
    function edit($idpagamentopedidodelivery)
    {   
        // check if the pagamentopedidodelivery exists before trying to edit it
        $data['pagamentopedidodelivery'] = $this->Pagamentopedidodelivery_model->get_pagamentopedidodelivery($idpagamentopedidodelivery);
        
        if(isset($data['pagamentopedidodelivery']['idpagamentopedidodelivery']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idpedidodelivery' => $this->input->post('idpedidodelivery'),
					'valor' => $this->input->post('valor'),
					'descricao' => $this->input->post('descricao'),
					'idformapagamento' => $this->input->post('idformapagamento'),
					'data' => $this->input->post('data'),
					'tipomovimentacao' => $this->input->post('tipomovimentacao'),
					'usuario_id' => $this->input->post('usuario_id'),
					'formapgto' => $this->input->post('formapgto'),
                );

                $this->Pagamentopedidodelivery_model->update_pagamentopedidodelivery($idpagamentopedidodelivery,$params);            
                redirect('pagamentopedidodelivery/index');
            }
            else
            {
                $data['_view'] = 'pagamentopedidodelivery/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pagamentopedidodelivery you are trying to edit does not exist.');
    } 

    /*
     * Deleting pagamentopedidodelivery
     */
    function remove($idpagamentopedidodelivery)
    {
        $pagamentopedidodelivery = $this->Pagamentopedidodelivery_model->get_pagamentopedidodelivery($idpagamentopedidodelivery);

        // check if the pagamentopedidodelivery exists before trying to delete it
        if(isset($pagamentopedidodelivery['idpagamentopedidodelivery']))
        {
            $this->Pagamentopedidodelivery_model->delete_pagamentopedidodelivery($idpagamentopedidodelivery);
            redirect('pagamentopedidodelivery/index');
        }
        else
            show_error('The pagamentopedidodelivery you are trying to delete does not exist.');
    }
    
}
