<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pedidopdv extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pedidopdv_model');
        $this->load->model('Itenspedidopdv_model');
          $this->load->model('Entradaproduto_model');
    }

    /*
     * Listing of pedidopdv
     */
    function index()
    {

      date_default_timezone_set('America/Sao_Paulo');
      $data = date('d/m/Y');
      $hora = date('H:i');
    $params = array(
          'data'=>$data,
          'hora'=>$hora

    );
      $pedido = $this->Pedidopdv_model->novavenda($params);




        redirect('pedidopdv/editapdv/'.$pedido);

    }

    public function desconto(){

        $pedidopdvid =  $this->input->post('formdescontoid');
        $desconto =  $this->input->post('descontovalor');

$null= $this->Pedidopdv_model->desconto($pedidopdvid,$desconto);

  echo json_encode(array('result'=> true));


    }

    public function editapdv($pedido){

      $data['pdv']= $this->Pedidopdv_model->getvenda($pedido);
    $data['itenspdv']= $this->Itenspedidopdv_model->getitens($pedido);
  //  $data['totalitens'] = $this->Pdv_model->totalpedido($pedido);
  //  $data['pagamento'] = $this->Pdv_model->getpagamento($pedido);
$data['formpago']=$this->Pedidopdv_model->getpagamento($pedido);
  //    $this->load->view('include/header');
      $this->load->view('pedidopdv/index',$data);
  //    $this->load->view('include/footer');


    }
    /*
     * Adding a new pedidopdv
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'data' => $this->input->post('data'),
				'hora' => $this->input->post('hora'),
				'subtotal' => $this->input->post('subtotal'),
				'desconto' => $this->input->post('desconto'),
				'cliente_id' => $this->input->post('cliente_id'),
				'pago' => $this->input->post('pago'),
				'horafechamento' => $this->input->post('horafechamento'),
				'usuarioid' => $this->input->post('usuarioid'),
            );

            $pedidopdv_id = $this->Pedidopdv_model->add_pedidopdv($params);
            redirect('pedidopdv/index');
        }
        else
        {
            $data['_view'] = 'pedidopdv/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a pedidopdv
     */
    function edit($idpedidopdv)
    {
        // check if the pedidopdv exists before trying to edit it
        $data['pedidopdv'] = $this->Pedidopdv_model->get_pedidopdv($idpedidopdv);

        if(isset($data['pedidopdv']['idpedidopdv']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'data' => $this->input->post('data'),
					'hora' => $this->input->post('hora'),
					'subtotal' => $this->input->post('subtotal'),
					'desconto' => $this->input->post('desconto'),
					'cliente_id' => $this->input->post('cliente_id'),
					'pago' => $this->input->post('pago'),
					'horafechamento' => $this->input->post('horafechamento'),
					'usuarioid' => $this->input->post('usuarioid'),
                );

                $this->Pedidopdv_model->update_pedidopdv($idpedidopdv,$params);
                redirect('pedidopdv/index');
            }
            else
            {
                $data['_view'] = 'pedidopdv/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pedidopdv you are trying to edit does not exist.');
    }

    /*
     * Deleting pedidopdv
     */
    function remove($idpedidopdv)
    {
        $pedidopdv = $this->Pedidopdv_model->get_pedidopdv($idpedidopdv);

        // check if the pedidopdv exists before trying to delete it

        $estoque = $this->Itenspedidopdv_model->getitensestoque($idpedidopdv);

           foreach ($estoque as $row){
        $params = array(
          'id_produto'=> $row['produto_id'],
          'qtde'=> $row['quantidade']
        );
      }
      $this->Entradaproduto_model->entrada($params);
                $this->Itenspedidopdv_model->delete_pedido($idpedidopdv);
            $this->Pedidopdv_model->delete_pedidopdv($idpedidopdv);
            redirect('pedidopdv/index');
}

}
