<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pedidomesa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pedidomesa_model');
          $this->load->model('Mesasaberta_model');
            $this->load->model('Empresa_model');
            $this->load->model('Produto_model');
                $this->load->model('Categoria_model');
                    $this->load->model('Itenspedidomesa_model');
    }

    /*
     * Listing of pedidomesas
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('pedidomesa/index?');
        $config['total_rows'] = $this->Pedidomesa_model->get_all_pedidomesas_count();
        $this->pagination->initialize($config);

        $data['pedidomesas'] = $this->Pedidomesa_model->get_all_pedidomesas($params);
          $data['numerodemesas'] = $this->Empresa_model->get_empresamesa();
        $data['mesasabertas'] = $this->Mesasaberta_model->get_all_mesasabertas();

        $data['_view'] = 'pedidomesa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pedidomesa
     */

     function mesaaberta(){

$pedido = $this->input->post('idpedidomesa');
          redirect('pedidomesa/editapedido/'.$pedido);

     }

     function novamesa(){



$numeromesa = $this->input->post('numeromesa');

$pedidoaberto = $this->Pedidomesa_model->verificapedido($numeromesa);

if($pedidoaberto!=null){

  redirect('pedidomesa/editapedido/'.$pedidoaberto);
}
else{
       date_default_timezone_set('America/Sao_Paulo');
       $data = date('d/m/Y');
       $hora = date('H:i');
      // $numeromesa = $this->input->post('numeromesa');

    //   $idpedidomesa = '1';

         $params = array(
              'data'=>$data,
              'horaabertura'=>$hora,
              'numeromesa'=>$numeromesa
         );

         $pedido = $this->Pedidomesa_model->add_pedidomesa($params);

$mesaaberta = array(
      'numeromesa'=>$numeromesa,
      'idpedidomesa' => $pedido,
      'dataabertura'=> $data,
      'horaabertura' =>$hora

);

 $null=$this->Mesasaberta_model->add_mesasaberta($mesaaberta);


redirect('pedidomesa/editapedido/'.$pedido);
//redirect('pedidomesa/edit',$pedido);

  //echo json_encode(array('result'=> true));

      //    $data['_view'] = 'pedidomesa/novo';

}



     }
     function testenovaview(){
       $this->load->view('pedidomesa/pedidomesa');

     }

     function editapedido($pedido){

       $data['pedidomesa'] = $this->Pedidomesa_model->get_pedidomesa($pedido);
        $data['itenspedidomesa'] = $this->Itenspedidomesa_model->get_itenspedidomesa($pedido);

      $data['empresa'] = $this->Empresa_model->get_empresamesa();
       //$this->$data['pedidomesa'] = $this->Pedidomesa_model->get_pedidomesa($pedido);


       $data['produtos'] = $this->Produto_model->get_todos();
$data['categoria'] = $this->Categoria_model->get_todos();
       //  $data['_view'] = 'pedidomesa/novo';
       //    $this->load->view('pedidomesa/novo',$this->$data);
$this->load->view('pedidomesa/pedidomesa',$data);
          // $data['_view'] = 'pedidomesa/novo';
      //     $this->load->view('layouts/main',$data);

     }
    function add()
    {
    /*    if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'data' => $this->input->post('data'),
				'numeromesa' => $this->input->post('numeromesa'),
				'idclientes' => $this->input->post('idclientes'),
				'subtotal' => $this->input->post('subtotal'),
				'taxaservico' => $this->input->post('taxaservico'),
				'desconto' => $this->input->post('desconto'),
				'pago' => $this->input->post('pago'),
				'horaabertura' => $this->input->post('horaabertura'),
				'horafechamento' => $this->input->post('horafechamento'),
				'pessoasmesa' => $this->input->post('pessoasmesa'),
				'totalpago' => $this->input->post('totalpago'),
				'valoremaberto' => $this->input->post('valoremaberto'),
            );

            $pedidomesa_id = $this->Pedidomesa_model->add_pedidomesa($params);
            redirect('pedidomesa/index');
        }
        else
        { */
            $data['_view'] = 'pedidomesa/novo';
            $this->load->view('layouts/main');
    //   }
    }

    /*
     * Editing a pedidomesa
     */
    function edit($idpedidomesa)
    {
        // check if the pedidomesa exists before trying to edit it
        $data['pedidomesa'] = $this->Pedidomesa_model->get_pedidomesa($idpedidomesa);

        //$this->$data['pedidomesa'] = $this->Pedidomesa_model->get_pedidomesa($pedido);


        $data['produtos'] = $this->Produto_model->get_all_produtos();

        //  $data['_view'] = 'pedidomesa/novo';
        //    $this->load->view('pedidomesa/novo',$this->$data);

            $data['_view'] = 'pedidomesa/novo';
            $this->load->view('layouts/main',$data);

    }

    /*
     * Deleting pedidomesa
     */
    function excluirpedido()
    {
$idpedidomesa = $this->input->post('idpedidomesa');
      				$this->Itenspedidomesa_model->delete_itempedidomesa($idpedidomesa);
      				$this->Pedidomesa_model->delete_pedidomesa($idpedidomesa);
      $this->Mesasaberta_model->delete_mesasaberta($idpedidomesa);
      echo json_encode(array('result'=> true));
    }

}
