<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tamanhopizza extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tamanhopizza_model');
    } 

    /*
     * Listing of tamanhopizza
     */
    function index()
    {
        $data['tamanhopizza'] = $this->Tamanhopizza_model->get_all_tamanhopizza();
        
        $data['_view'] = 'tamanhopizza/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tamanhopizza
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idpizza' => $this->input->post('idpizza'),
				'tamanho' => $this->input->post('tamanho'),
				'custo' => $this->input->post('custo'),
				'venda' => $this->input->post('venda'),
				'siglatamanho' => $this->input->post('siglatamanho'),
				'impressora' => $this->input->post('impressora'),
				'tipocobranca' => $this->input->post('tipocobranca'),
            );
            
            $tamanhopizza_id = $this->Tamanhopizza_model->add_tamanhopizza($params);
            redirect('tamanhopizza/index');
        }
        else
        {            
            $data['_view'] = 'tamanhopizza/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tamanhopizza
     */
    function edit($idtamanhopizza)
    {   
        // check if the tamanhopizza exists before trying to edit it
        $data['tamanhopizza'] = $this->Tamanhopizza_model->get_tamanhopizza($idtamanhopizza);
        
        if(isset($data['tamanhopizza']['idtamanhopizza']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idpizza' => $this->input->post('idpizza'),
					'tamanho' => $this->input->post('tamanho'),
					'custo' => $this->input->post('custo'),
					'venda' => $this->input->post('venda'),
					'siglatamanho' => $this->input->post('siglatamanho'),
					'impressora' => $this->input->post('impressora'),
					'tipocobranca' => $this->input->post('tipocobranca'),
                );

                $this->Tamanhopizza_model->update_tamanhopizza($idtamanhopizza,$params);            
                redirect('tamanhopizza/index');
            }
            else
            {
                $data['_view'] = 'tamanhopizza/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tamanhopizza you are trying to edit does not exist.');
    } 

    /*
     * Deleting tamanhopizza
     */
    function remove($idtamanhopizza)
    {
        $tamanhopizza = $this->Tamanhopizza_model->get_tamanhopizza($idtamanhopizza);

        // check if the tamanhopizza exists before trying to delete it
        if(isset($tamanhopizza['idtamanhopizza']))
        {
            $this->Tamanhopizza_model->delete_tamanhopizza($idtamanhopizza);
            redirect('tamanhopizza/index');
        }
        else
            show_error('The tamanhopizza you are trying to delete does not exist.');
    }
    
}
