<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Taxaentrega extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Taxaentrega_model');
    } 

    /*
     * Listing of taxaentrega
     */
    function index()
    {
        $data['taxaentrega'] = $this->Taxaentrega_model->get_all_taxaentrega();
        
        $data['_view'] = 'taxaentrega/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new taxaentrega
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nome' => $this->input->post('nome'),
				'valor' => $this->input->post('valor'),
            );
            
            $taxaentrega_id = $this->Taxaentrega_model->add_taxaentrega($params);
            redirect('taxaentrega/index');
        }
        else
        {            
            $data['_view'] = 'taxaentrega/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a taxaentrega
     */
    function edit($idtaxaentrega)
    {   
        // check if the taxaentrega exists before trying to edit it
        $data['taxaentrega'] = $this->Taxaentrega_model->get_taxaentrega($idtaxaentrega);
        
        if(isset($data['taxaentrega']['idtaxaentrega']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nome' => $this->input->post('nome'),
					'valor' => $this->input->post('valor'),
                );

                $this->Taxaentrega_model->update_taxaentrega($idtaxaentrega,$params);            
                redirect('taxaentrega/index');
            }
            else
            {
                $data['_view'] = 'taxaentrega/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The taxaentrega you are trying to edit does not exist.');
    } 

    /*
     * Deleting taxaentrega
     */
    function remove($idtaxaentrega)
    {
        $taxaentrega = $this->Taxaentrega_model->get_taxaentrega($idtaxaentrega);

        // check if the taxaentrega exists before trying to delete it
        if(isset($taxaentrega['idtaxaentrega']))
        {
            $this->Taxaentrega_model->delete_taxaentrega($idtaxaentrega);
            redirect('taxaentrega/index');
        }
        else
            show_error('The taxaentrega you are trying to delete does not exist.');
    }
    
}
