<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adicional_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get adicional by idadicionais
     */
    function get_adicional($idadicionais)
    {
        return $this->db->get_where('adicionais',array('idadicionais'=>$idadicionais))->row_array();
    }
    
    /*
     * Get all adicionais count
     */
    function get_all_adicionais_count()
    {
        $this->db->from('adicionais');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all adicionais
     */
    function get_all_adicionais($params = array())
    {
        $this->db->order_by('idadicionais', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('adicionais')->result_array();
    }
        
    /*
     * function to add new adicional
     */
    function add_adicional($params)
    {
        $this->db->insert('adicionais',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update adicional
     */
    function update_adicional($idadicionais,$params)
    {
        $this->db->where('idadicionais',$idadicionais);
        return $this->db->update('adicionais',$params);
    }
    
    /*
     * function to delete adicional
     */
    function delete_adicional($idadicionais)
    {
        return $this->db->delete('adicionais',array('idadicionais'=>$idadicionais));
    }
}
