<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Caixa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get caixa by idcaixa
     */
    function get_caixa($idcaixa)
    {
        return $this->db->get_where('caixa',array('idcaixa'=>$idcaixa))->row_array();
    }
        
    /*
     * Get all caixa
     */
    function get_all_caixa()
    {
        $this->db->order_by('idcaixa', 'desc');
        return $this->db->get('caixa')->result_array();
    }
        
    /*
     * function to add new caixa
     */
    function add_caixa($params)
    {
        $this->db->insert('caixa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update caixa
     */
    function update_caixa($idcaixa,$params)
    {
        $this->db->where('idcaixa',$idcaixa);
        return $this->db->update('caixa',$params);
    }
    
    /*
     * function to delete caixa
     */
    function delete_caixa($idcaixa)
    {
        return $this->db->delete('caixa',array('idcaixa'=>$idcaixa));
    }
}
