<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Categoria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get categoria by idcategoria
     */
    function get_categoria($idcategoria)
    {
        return $this->db->get_where('categoria',array('idcategoria'=>$idcategoria))->row_array();
    }

    /*
     * Get all categorias count
     */
    function get_all_categorias_count()
    {
        $this->db->from('categoria');
        return $this->db->count_all_results();
    }

    function get_todos()
    {
      $sql = "select * from categoria";
      $query = $this->db->query($sql);
      $array = $query->result_array();
      return $array;
    }

    /*
     * Get all categorias
     */
    function get_all_categorias($params = array())
    {
        $this->db->order_by('idcategoria', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('categoria')->result_array();
    }

    /*
     * function to add new categoria
     */
    function add_categoria($params)
    {
        $this->db->insert('categoria',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update categoria
     */
    function update_categoria($idcategoria,$params)
    {
        $this->db->where('idcategoria',$idcategoria);
        return $this->db->update('categoria',$params);
    }

    /*
     * function to delete categoria
     */
    function delete_categoria($idcategoria)
    {
        return $this->db->delete('categoria',array('idcategoria'=>$idcategoria));
    }
}
