<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Controlesistema_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function getsistema(){

      $otherdb = $this->load->database('sistema', TRUE);

        return $otherdb->get('licencasistema')->row_array();
    }

  }
