<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contasapagar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get contaapagar by idcontasapagar
     */
    function get_contaapagar($idcontasapagar)
    {
        return $this->db->get_where('contasapagar',array('idcontasapagar'=>$idcontasapagar))->row_array();
    }
    
    /*
     * Get all contasapagar count
     */
    function get_all_contasapagar_count()
    {
        $this->db->from('contasapagar');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all contasapagar
     */
    function get_all_contasapagar($params = array())
    {
        $this->db->order_by('idcontasapagar', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('contasapagar')->result_array();
    }
        
    /*
     * function to add new contaapagar
     */
    function add_contaapagar($params)
    {
        $this->db->insert('contasapagar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update contaapagar
     */
    function update_contaapagar($idcontasapagar,$params)
    {
        $this->db->where('idcontasapagar',$idcontasapagar);
        return $this->db->update('contasapagar',$params);
    }
    
    /*
     * function to delete contaapagar
     */
    function delete_contaapagar($idcontasapagar)
    {
        return $this->db->delete('contasapagar',array('idcontasapagar'=>$idcontasapagar));
    }
}
