<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Entregador_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get entregador by identregador
     */
    function get_entregador($identregador)
    {
        return $this->db->get_where('entregadores',array('identregador'=>$identregador))->row_array();
    }
    
    /*
     * Get all entregadores count
     */
    function get_all_entregadores_count()
    {
        $this->db->from('entregadores');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all entregadores
     */
    function get_all_entregadores($params = array())
    {
        $this->db->order_by('identregador', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('entregadores')->result_array();
    }
        
    /*
     * function to add new entregador
     */
    function add_entregador($params)
    {
        $this->db->insert('entregadores',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update entregador
     */
    function update_entregador($identregador,$params)
    {
        $this->db->where('identregador',$identregador);
        return $this->db->update('entregadores',$params);
    }
    
    /*
     * function to delete entregador
     */
    function delete_entregador($identregador)
    {
        return $this->db->delete('entregadores',array('identregador'=>$identregador));
    }
}
