<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Entradaproduto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function entrada($params)
    {
        $this->db->insert('entrada_produto',$params);
        return $this->db->insert_id();
    }

  }
