<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Formaspagamento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get formapagamento by idformaspagamento
     */
    function get_formapagamento($idformaspagamento)
    {
        return $this->db->get_where('formaspagamento',array('idformaspagamento'=>$idformaspagamento))->row_array();
    }
    
    /*
     * Get all formaspagamento count
     */
    function get_all_formaspagamento_count()
    {
        $this->db->from('formaspagamento');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all formaspagamento
     */
    function get_all_formaspagamento($params = array())
    {
        $this->db->order_by('idformaspagamento', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('formaspagamento')->result_array();
    }
        
    /*
     * function to add new formapagamento
     */
    function add_formapagamento($params)
    {
        $this->db->insert('formaspagamento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update formapagamento
     */
    function update_formapagamento($idformaspagamento,$params)
    {
        $this->db->where('idformaspagamento',$idformaspagamento);
        return $this->db->update('formaspagamento',$params);
    }
    
    /*
     * function to delete formapagamento
     */
    function delete_formapagamento($idformaspagamento)
    {
        return $this->db->delete('formaspagamento',array('idformaspagamento'=>$idformaspagamento));
    }
}
