<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Inventario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get inventario by idinventario
     */
    function get_inventario($idinventario)
    {
        return $this->db->get_where('inventario',array('idinventario'=>$idinventario))->row_array();
    }
    
    /*
     * Get all inventarios count
     */
    function get_all_inventarios_count()
    {
        $this->db->from('inventario');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all inventarios
     */
    function get_all_inventarios($params = array())
    {
        $this->db->order_by('idinventario', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('inventario')->result_array();
    }
        
    /*
     * function to add new inventario
     */
    function add_inventario($params)
    {
        $this->db->insert('inventario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update inventario
     */
    function update_inventario($idinventario,$params)
    {
        $this->db->where('idinventario',$idinventario);
        return $this->db->update('inventario',$params);
    }
    
    /*
     * function to delete inventario
     */
    function delete_inventario($idinventario)
    {
        return $this->db->delete('inventario',array('idinventario'=>$idinventario));
    }
}
