<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itensinventario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get iteminventario by iditensinventario
     */
    function get_iteminventario($iditensinventario)
    {
        return $this->db->get_where('itensinventario',array('iditensinventario'=>$iditensinventario))->row_array();
    }
    
    /*
     * Get all itensinventario count
     */
    function get_all_itensinventario_count()
    {
        $this->db->from('itensinventario');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all itensinventario
     */
    function get_all_itensinventario($params = array())
    {
        $this->db->order_by('iditensinventario', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('itensinventario')->result_array();
    }
        
    /*
     * function to add new iteminventario
     */
    function add_iteminventario($params)
    {
        $this->db->insert('itensinventario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update iteminventario
     */
    function update_iteminventario($iditensinventario,$params)
    {
        $this->db->where('iditensinventario',$iditensinventario);
        return $this->db->update('itensinventario',$params);
    }
    
    /*
     * function to delete iteminventario
     */
    function delete_iteminventario($iditensinventario)
    {
        return $this->db->delete('itensinventario',array('iditensinventario'=>$iditensinventario));
    }
}
