<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itenspedidodelivery_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get itempedidodelivery by iditenspedidodelivey
     */
    function get_itempedidodelivery($iditenspedidodelivey)
    {
        return $this->db->get_where('itenspedidodelivery',array('iditenspedidodelivey'=>$iditenspedidodelivey))->row_array();
    }
    
    /*
     * Get all itenspedidodelivery count
     */
    function get_all_itenspedidodelivery_count()
    {
        $this->db->from('itenspedidodelivery');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all itenspedidodelivery
     */
    function get_all_itenspedidodelivery($params = array())
    {
        $this->db->order_by('iditenspedidodelivey', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('itenspedidodelivery')->result_array();
    }
        
    /*
     * function to add new itempedidodelivery
     */
    function add_itempedidodelivery($params)
    {
        $this->db->insert('itenspedidodelivery',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update itempedidodelivery
     */
    function update_itempedidodelivery($iditenspedidodelivey,$params)
    {
        $this->db->where('iditenspedidodelivey',$iditenspedidodelivey);
        return $this->db->update('itenspedidodelivery',$params);
    }
    
    /*
     * function to delete itempedidodelivery
     */
    function delete_itempedidodelivery($iditenspedidodelivey)
    {
        return $this->db->delete('itenspedidodelivery',array('iditenspedidodelivey'=>$iditenspedidodelivey));
    }
}
