<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get menu by idtipodevendas
     */
    function get_menu($idtipodevendas)
    {
        return $this->db->get_where('menu',array('idtipodevendas'=>$idtipodevendas))->row_array();
    }
    
    /*
     * Get all menu count
     */
    function get_all_menu_count()
    {
        $this->db->from('menu');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all menu
     */
    function get_all_menu($params = array())
    {
        $this->db->order_by('idtipodevendas', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('menu')->result_array();
    }
        
    /*
     * function to add new menu
     */
    function add_menu($params)
    {
        $this->db->insert('menu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update menu
     */
    function update_menu($idtipodevendas,$params)
    {
        $this->db->where('idtipodevendas',$idtipodevendas);
        return $this->db->update('menu',$params);
    }
    
    /*
     * function to delete menu
     */
    function delete_menu($idtipodevendas)
    {
        return $this->db->delete('menu',array('idtipodevendas'=>$idtipodevendas));
    }
}
