<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Mesasaberta_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get mesasaberta by idmesasabertas
     */
    function get_mesasaberta($idmesasabertas)
    {
        return $this->db->get_where('mesasabertas',array('idmesasabertas'=>$idmesasabertas))->row_array();
    }

    /*
     * Get all mesasabertas count
     */
    function get_all_mesasabertas_count()
    {
        $this->db->from('mesasabertas');
        return $this->db->count_all_results();
    }

    /*
     * Get all mesasabertas
     */
    function get_all_mesasabertas($params = array())
    {
        $this->db->order_by('numeromesa', 'ASC');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('mesasabertas')->result_array();
    }

    /*
     * function to add new mesasaberta
     */
    function add_mesasaberta($params)
    {
        $this->db->insert('mesasabertas',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update mesasaberta
     */
    function update_mesasaberta($idmesasabertas,$params)
    {
        $this->db->where('idmesasabertas',$idmesasabertas);
        return $this->db->update('mesasabertas',$params);
    }

    /*
     * function to delete mesasaberta
     */
    function delete_mesasaberta($idmesasabertas)
    {
        return $this->db->delete('mesasabertas',array('idpedidomesa'=>$idmesasabertas));
    }
}
