<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Observaco_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get observacao by idobservacoes
     */
    function get_observacao($idobservacoes)
    {
        return $this->db->get_where('observacoes',array('idobservacoes'=>$idobservacoes))->row_array();
    }
    
    /*
     * Get all observacoes count
     */
    function get_all_observacoes_count()
    {
        $this->db->from('observacoes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all observacoes
     */
    function get_all_observacoes($params = array())
    {
        $this->db->order_by('idobservacoes', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('observacoes')->result_array();
    }
        
    /*
     * function to add new observacao
     */
    function add_observacao($params)
    {
        $this->db->insert('observacoes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update observacao
     */
    function update_observacao($idobservacoes,$params)
    {
        $this->db->where('idobservacoes',$idobservacoes);
        return $this->db->update('observacoes',$params);
    }
    
    /*
     * function to delete observacao
     */
    function delete_observacao($idobservacoes)
    {
        return $this->db->delete('observacoes',array('idobservacoes'=>$idobservacoes));
    }
}
