<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Opcoesitempedidodelivery_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get opcoesitempedidodelivery by idopcoesitempedidomesa
     */
    function get_opcoesitempedidodelivery($idopcoesitempedidomesa)
    {
        return $this->db->get_where('opcoesitempedidodelivery',array('idopcoesitempedidomesa'=>$idopcoesitempedidomesa))->row_array();
    }
        
    /*
     * Get all opcoesitempedidodelivery
     */
    function get_all_opcoesitempedidodelivery()
    {
        $this->db->order_by('idopcoesitempedidomesa', 'desc');
        return $this->db->get('opcoesitempedidodelivery')->result_array();
    }
        
    /*
     * function to add new opcoesitempedidodelivery
     */
    function add_opcoesitempedidodelivery($params)
    {
        $this->db->insert('opcoesitempedidodelivery',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update opcoesitempedidodelivery
     */
    function update_opcoesitempedidodelivery($idopcoesitempedidomesa,$params)
    {
        $this->db->where('idopcoesitempedidomesa',$idopcoesitempedidomesa);
        return $this->db->update('opcoesitempedidodelivery',$params);
    }
    
    /*
     * function to delete opcoesitempedidodelivery
     */
    function delete_opcoesitempedidodelivery($idopcoesitempedidomesa)
    {
        return $this->db->delete('opcoesitempedidodelivery',array('idopcoesitempedidomesa'=>$idopcoesitempedidomesa));
    }
}
