<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pagamentopedidodelivery_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pagamentopedidodelivery by idpagamentopedidodelivery
     */
    function get_pagamentopedidodelivery($idpagamentopedidodelivery)
    {
        return $this->db->get_where('pagamentopedidodelivery',array('idpagamentopedidodelivery'=>$idpagamentopedidodelivery))->row_array();
    }
        
    /*
     * Get all pagamentopedidodelivery
     */
    function get_all_pagamentopedidodelivery()
    {
        $this->db->order_by('idpagamentopedidodelivery', 'desc');
        return $this->db->get('pagamentopedidodelivery')->result_array();
    }
        
    /*
     * function to add new pagamentopedidodelivery
     */
    function add_pagamentopedidodelivery($params)
    {
        $this->db->insert('pagamentopedidodelivery',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pagamentopedidodelivery
     */
    function update_pagamentopedidodelivery($idpagamentopedidodelivery,$params)
    {
        $this->db->where('idpagamentopedidodelivery',$idpagamentopedidodelivery);
        return $this->db->update('pagamentopedidodelivery',$params);
    }
    
    /*
     * function to delete pagamentopedidodelivery
     */
    function delete_pagamentopedidodelivery($idpagamentopedidodelivery)
    {
        return $this->db->delete('pagamentopedidodelivery',array('idpagamentopedidodelivery'=>$idpagamentopedidodelivery));
    }
}
