<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pagamentopedidopdv_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get pagamentopedidopdv by idpagamentopedidomesa
     */
    function get_pagamentopedidopdv($idpagamentopedidomesa)
    {
        return $this->db->get_where('pagamentopedidopdv',array('idpagamentopedidomesa'=>$idpagamentopedidomesa))->row_array();
    }

    /*
     * Get all pagamentopedidopdv
     */

     function pagopdv($idpedidopdv){

       $sql = "SELECT sum(valor) as pago from pagamentopedidopdv where idpedidopdv='$idpedidopdv'";
       $query = $this->db->query($sql);

       if ($query->num_rows() == 1)
       {
       //Use row() to get a single result
       $row = $query->row();

       //$row will now have if you printed the contents:
       //print_r( $row );
       //stdClass Object ( [email] => example@gmail.com )

       //Pass $query->email directly to reset_password

       return $row->pago;
     }
     }
    function get_all_pagamentopedidopdv()
    {
        $this->db->order_by('idpagamentopedidomesa', 'desc');
        return $this->db->get('pagamentopedidopdv')->result_array();
    }

    /*
     * function to add new pagamentopedidopdv
     */
    function add_pagamentopedidopdv($params)
    {
        $this->db->insert('pagamentopedidopdv',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update pagamentopedidopdv
     */
    function update_pagamentopedidopdv($idpagamentopedidomesa,$params)
    {
        $this->db->where('idpagamentopedidomesa',$idpagamentopedidomesa);
        return $this->db->update('pagamentopedidopdv',$params);
    }

    /*
     * function to delete pagamentopedidopdv
     */
    function delete_pagamentopedidopdv($idpagamentopedidomesa)
    {
        return $this->db->delete('pagamentopedidopdv',array('idpagamentopedidomesa'=>$idpagamentopedidomesa));
    }
}
