<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pedidopdv_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get pedidopdv by idpedidopdv
     */
    function get_pedidopdv($idpedidopdv)
    {
        return $this->db->get_where('pedidopdv',array('idpedidopdv'=>$idpedidopdv))->row_array();
    }
    public function novavenda($params){


      $this->db->insert('pedidopdv',$params);

    return $this->db->insert_id();

    }

    public function getvenda($id){

      $this->db->select('*');
     $this->db->from('pedidopdv');
     $this->db->where('idpedidopdv', $id);

     $query = $this->db->get();

     if ($query->num_rows() == 1){


    $row = $query->row();


    return $row;
    }
      }
    /*
     * Get all pedidopdv
     */
    function get_all_pedidopdv()
    {
        $this->db->order_by('idpedidopdv', 'desc');
        return $this->db->get('pedidopdv')->result_array();
    }

    /*
     * function to add new pedidopdv
     */
    function add_pedidopdv($params)
    {
        $this->db->insert('pedidopdv',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update pedidopdv
     */
    function update_pedidopdv($idpedidopdv,$params)
    {
        $this->db->where('idpedidopdv',$idpedidopdv);
        return $this->db->update('pedidopdv',$params);
    }

    /*
     * function to delete pedidopdv
     */
    function delete_pedidopdv($idpedidopdv)
    {
        return $this->db->delete('pedidopdv',array('idpedidopdv'=>$idpedidopdv));
    }
}
