<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pedidomesa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get pedidomesa by idpedidomesa
     */
    function get_pedidomesa($idpedidomesa)
    {
        return $this->db->get_where('pedidomesa',array('idpedidomesa'=>$idpedidomesa))->row_array();
    }

    /*
     * Get all pedidomesas count
     */


     function verificapedido($numeromesa){

       $this->db->select('*');
     $this->db->from('mesasabertas');
     $this->db->where('numeromesa', $numeromesa);

     $this->db->limit(1);

     $query = $this->db->get();

     if ($query->num_rows() == 1)
     {
     //Use row() to get a single result
     $row = $query->row();

     //$row will now have if you printed the contents:
     //print_r( $row );
     //stdClass Object ( [email] => example@gmail.com )

     //Pass $query->email directly to reset_password
     }
     return $row->idpedidomesa;

     }
    function get_all_pedidomesas_count()
    {
        $this->db->from('pedidomesa');
        return $this->db->count_all_results();
    }

    /*
     * Get all pedidomesas
     */
    function get_all_pedidomesas($params = array())
    {
        $this->db->order_by('idpedidomesa', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('pedidomesa')->result_array();
    }

    /*
     * function to add new pedidomesa
     */
    function add_pedidomesa($params)
    {
        $this->db->insert('pedidomesa',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update pedidomesa
     */
    function update_pedidomesa($idpedidomesa,$params)
    {
        $this->db->where('idpedidomesa',$idpedidomesa);
        return $this->db->update('pedidomesa',$params);
    }

    public function atualizatotalpago($idpedidomesa,$totalpago){
      $this->db->set('totalpago',$totalpago);
      $this->db->where('idpedidomesa',$idpedidomesa);
      $this->db->update('pedidomesa');

      return TRUE;
    }

    /*
     * function to delete pedidomesa
     */
    function delete_pedidomesa($idpedidomesa)
    {
        return $this->db->delete('pedidomesa',array('idpedidomesa'=>$idpedidomesa));
    }
}
