<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pizza_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pizza by idpizza
     */
    function get_pizza($idpizza)
    {
        return $this->db->get_where('pizza',array('idpizza'=>$idpizza))->row_array();
    }
        
    /*
     * Get all pizza
     */
    function get_all_pizza()
    {
        $this->db->order_by('idpizza', 'desc');
        return $this->db->get('pizza')->result_array();
    }
        
    /*
     * function to add new pizza
     */
    function add_pizza($params)
    {
        $this->db->insert('pizza',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pizza
     */
    function update_pizza($idpizza,$params)
    {
        $this->db->where('idpizza',$idpizza);
        return $this->db->update('pizza',$params);
    }
    
    /*
     * function to delete pizza
     */
    function delete_pizza($idpizza)
    {
        return $this->db->delete('pizza',array('idpizza'=>$idpizza));
    }
}
