<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Taxaentrega_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get taxaentrega by idtaxaentrega
     */
    function get_taxaentrega($idtaxaentrega)
    {
        return $this->db->get_where('taxaentrega',array('idtaxaentrega'=>$idtaxaentrega))->row_array();
    }
        
    /*
     * Get all taxaentrega
     */
    function get_all_taxaentrega()
    {
        $this->db->order_by('idtaxaentrega', 'desc');
        return $this->db->get('taxaentrega')->result_array();
    }
        
    /*
     * function to add new taxaentrega
     */
    function add_taxaentrega($params)
    {
        $this->db->insert('taxaentrega',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update taxaentrega
     */
    function update_taxaentrega($idtaxaentrega,$params)
    {
        $this->db->where('idtaxaentrega',$idtaxaentrega);
        return $this->db->update('taxaentrega',$params);
    }
    
    /*
     * function to delete taxaentrega
     */
    function delete_taxaentrega($idtaxaentrega)
    {
        return $this->db->delete('taxaentrega',array('idtaxaentrega'=>$idtaxaentrega));
    }
}
